import "./globals.css";
import type { Metadata } from "next";
import SessionAuthProvider from "@/src/context/SessionAuthProvider";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Welcome to TravelTo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>{children} </body>
=======
      <body className={inter.className}>
        <SessionAuthProvider>{children}</SessionAuthProvider>
      </body>
>>>>>>> e777bff13042260087251fe51e11175fdef2eebb
    </html>
  );
}
