import "./globals.css";
import type { Metadata } from "next";
import SessionAuthProvider from "@/src/context/SessionAuthProvider";
import { Inter } from "next/font/google";
import Providers from "../redux/provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Welcome to TravelTo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <SessionAuthProvider>{children}</SessionAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
